"""Write the notebook table (Colab badges + measured runtimes) into README.md, between the markers.

    python3 scripts/gen_readme_table.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys_path = ROOT / "scripts"
import sys  # noqa: E402

sys.path.insert(0, str(sys_path))
from nb import colab_url  # noqa: E402

reg = json.loads((ROOT / "site/src/data/registry.json").read_text())
times = json.loads((ROOT / "notebooks/runtimes.json").read_text())
BADGE = "https://colab.research.google.com/assets/colab-badge.svg"


def row(label: str, path: str) -> str:
    t = times.get(path)
    run = f"{t['seconds'] / 60:.1f} min" if t and t["seconds"] >= 60 else (f"{t['seconds']:.0f} s" if t else "not run yet")
    exists = (ROOT / path).exists()
    badge = f"[![Open In Colab]({BADGE})]({colab_url(path)})" if exists else "(not written yet)"
    return f"| {label} | {badge} | [`{Path(path).name}`]({path}) | {run} |"


lines = ["| Notebook | Open | File | Runtime on the build machine (4-core CPU) |", "|---|---|---|---|"]
lines.append(row("Showpiece A: retrain the digit reader", "notebooks/showpieces/digits_retrain.ipynb"))
lines.append(row("Showpiece B: retrain the tiny language model", "notebooks/showpieces/tinylm_retrain.ipynb"))
for f in reg["fields"]:
    lines.append(row(f"Field {f['num']}: {f['title']}", f["notebook"]))
for d in reg["dsa"]:
    lines.append(row(f"DSA {d['num']}: {d['title']}", d["notebook"]))
table = "\n".join(lines)

readme = (ROOT / "README.md").read_text()
new = re.sub(r"(<!-- NOTEBOOK-TABLE:START -->\n).*?(\n<!-- NOTEBOOK-TABLE:END -->)",
             lambda m: m.group(1) + table + "\n\n*Generated by `python3 scripts/gen_readme_table.py`. Colab's free CPU is usually slower than the build machine.*" + m.group(2),
             readme, flags=re.S)
(ROOT / "README.md").write_text(new)
print(f"README table: {len(lines) - 2} notebooks")
